DIR		 :=$(TOPDIR)/tcp/server/dual_stack

EXE_NAME := dual_stack_tcp

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin

DEPS    := $(wildcard $(INC_DIR)/*.h)


include $(TOPDIR)/Makefile.include

