TOPDIR   := $(HOME)/personal-repos/Network-Programming
DIR		:=$(TOPDIR)/https/client/simple_https_client

EXE_NAME := simple_https_client

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin
LIBS := -lcrypto -lssl


include $(TOPDIR)/Makefile.include

