TOPDIR   := $(HOME)/personal-repos/Network-Programming
DIR		 :=$(TOPDIR)/tcp/server/tcp_server

EXE_NAME := tcp_server

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin

DEPS    := $(wildcard $(INC_DIR)/*.h)


include $(TOPDIR)/Makefile.include

