DIR		 := $(TOPDIR)/tcp/client

EXE_NAME := tcp_client

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin

DEPS    := $(wildcard $(INC_DIR)/*.h)


include $(TOPDIR)/Makefile.include

