TOPDIR   := $(HOME)/personal-repos/Network-Programming
DIR		:=$(TOPDIR)/udp/client

EXE_NAME := udp_client

SRC_DIR  := ./
INC_DIR  := $(DIR)/../include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin


include $(TOPDIR)/Makefile.include

