DIR		:=$(TOPDIR)/udp/server

EXE_NAME := udp_server

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin
LIBS := -lcrypto -lssl


include $(TOPDIR)/Makefile.include

