TOPDIR   := $(HOME)/personal-repos/Network-Programming
DIR		 := $(TOPDIR)/http/server

EXE_NAME := web_server

SRC_DIR  := ./
INC_DIR  := $(TOPDIR)/include
OBJDIR   := $(DIR)/obj
BINDIR   := $(DIR)/bin


include $(TOPDIR)/Makefile.include

